# fly.toml app configuration file generated for desplieguephyton on 2024-11-15T20:56:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'desplieguephyton'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DATABASE_URL = "postgresql://postgres:WagmpRkBjhOWUeVGrJbzINDQudyEZBqT@autorack.proxy.rlwy.net:13496/railway"
