# fly.toml app configuration file generated for fundamentos-trabajo-final

app = 'fundamentos-trabajo-final'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]  # Acepta conexiones HTTP

  [[services.ports]]
    port = 443
    handlers = ["tls"]  # Acepta conexiones HTTPS

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
